# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-connections: 400
    max-threads: 300

  port: 8088
  servlet:
    context-path: /eip

error:
  code: 106

http:
  maxTotal: 100
  defaultMaxPerRoute: 20
  connectTimeout: 1000
  connectionRequestTimeout: 500
  socketTimeout: 10000
  statleConnectionCheckEnabled: true

mq:
  returnMq:    http://commonatomapi.devops.inspur.com/common/productreturn
  pushMq:      http://tenantconservice.devops.inspur.com/console/websocket/v1/servers

openstackIp: 10.110.25.117

# Mysql

# 环境 dev|prod
spring:
  resources:
    # Swagger
    add-mappings: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://10.110.1.26:3306/icp_eip?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
      username: eip
      password: eip0914
      initialSize: 5
      minIdle: 3
      maxActive: 200
      maxWait: 60000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  data:
    rest:
      base-path: /dbstructapi

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

# KeyCloak
keycloak:
  enabled: true
  disable-trust-manager: true
  auth-server-url: https://iopdev.10.110.25.123.xip.io/auth
  realm: picp
  public-client: false
  credentials:
    secret: be97c023-1ad2-485f-b83d-d4a64af76758
  resource: bss-server
  ssl-required: none
  bearer-only: true
  cors: true
  cors-max-age: 1728000
  cors-allowed-headers: Authorization, Origin, X-Requested-With, Content-Type, X-Custom-Header
  cors-allowed-methods: GET,POST,PUT,DELETE,OPTIONS

# Logback
logging:
  config: classpath:logback.xml
