# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-connections: 400
    max-threads: 300

  port: 8088
  servlet:
    context-path: /eip

# 环境 dev|prod
spring:
  profiles:
    active: dev

error:
  code: 106

http:
  maxTotal: 100
  defaultMaxPerRoute: 20
  connectTimeout: 1000
  connectionRequestTimeout: 500
  socketTimeout: 10000
  statleConnectionCheckEnabled: true

bssURL:
  openstackIp: 10.110.25.117
  returnMq:    http://commonatomapi.devops.inspur.com/common/productreturn
  pushMq:      http://tenantconservice.devops.inspur.com/console/websocket/sendMessage
